name: Node.js Scheduled Task

on:
  schedule:
    # 每天北京时间 21:30 触发（即 UTC 13:30）
    - cron: '30 13 * * *'
  workflow_dispatch:  # 可手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
