name: Daily Node.js Task

on:
  schedule:
    - cron: '30 1 * * *'  # 每天北京时间 9:30（UTC时间 1:30）
  workflow_dispatch:  # 可手动触发

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies (if any)
        run: npm install

      - name: Run daily Node.js task
        run: node daily-task.js
