name: Node.js Scheduled Task

on:
  schedule:
    - cron: '30 1 * * *'  # 每天北京时间21:30
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Output time
        run: |
          echo "当前时间：" $(date)
